### ISSUE TITLE
GotoByteInFile(): Attempt to go before start of file.

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/foncier#36]
```
19/12/2016 11:24:50[2016-12-19 10:24:50,146: INFO/MainProcess] Received task: extraction.do[068b3b1c-b367-48d0-a52c-73281625f498]
19/12/2016 11:24:50[2016-12-19 10:24:50,269: INFO/PoolWorker-1] Successfully sent email to xxx@camptocamp.com
19/12/2016 11:24:50[2016-12-19 10:24:50,271: INFO/PoolWorker-1] Created temp dir /extracts/foncier_2014_mifmid_4326_068b3b1c-b367-48d0-a52c-73281625f498-v_ny9pfj
19/12/2016 11:33:22[2016-12-19 10:33:22,933: ERROR/PoolWorker-1] Command: ogr2ogr -where idcom IN ('59001','59002','59003','59004','59005', ... ,'62893','62894') -a_srs EPSG:4326 -t_srs EPSG:4326 -f MapInfo File /extracts/foncier_2014_mifmid_4326_068b3b1c-b367-48d0-a52c-73281625f498-v_ny9pfj PG:host=database port=5432 user=geoserver dbname=geoserver password=... schemas=foncier_2014 pb0010_local
19/12/2016 11:33:22[2016-12-19 10:33:22,939: ERROR/PoolWorker-1] Exit code: 1
19/12/2016 11:33:22[2016-12-19 10:33:22,940: ERROR/PoolWorker-1] STDOUT:
19/12/2016 11:33:22[2016-12-19 10:33:22,940: ERROR/PoolWorker-1] STDERR: ERROR 1: GotoByteInFile(): Attempt to go before start of file.
19/12/2016 11:33:22ERROR 3: Failed writing geometry for feature id 1832322 in /extracts/foncier_2014_mifmid_4326_068b3b1c-b367-48d0-a52c-73281625f498-v_ny9pfj/pb0010_local.tab
19/12/2016 11:33:22ERROR 1: Unable to write feature 1832321 from layer pb0010_local.
19/12/2016 11:33:22ERROR 1: Terminating translation prematurely after failed
19/12/2016 11:33:22translation of layer pb0010_local (use -skipfailures to skip errors)
19/12/2016 11:33:22[2016-12-19 10:33:22,964: ERROR/PoolWorker-1] Task extraction.do[068b3b1c-b367-48d0-a52c-73281625f498] raised unexpected: Exception("Error running ogr2ogr -where idcom IN ('59001','59002',','62893','62894') -a_srs EPSG:4326 -t_srs EPSG:4326 -f MapInfo File /extracts/foncier_2014_mifmid_4326_068b3b1c-b367-48d0-a52c-73281625f498-v_ny9pfj PG:host=database port=5432 user=geoserver dbname=geoserver password=... schemas=foncier_2014 pb0010_local",)
19/12/2016 11:33:22Traceback (most recent call last):
19/12/2016 11:33:22  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 368, in trace_task
19/12/2016 11:33:22    R = retval = fun(*args, **kwargs)
19/12/2016 11:33:22  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 623, in __protected_call__
19/12/2016 11:33:22    return self.run(*args, **kwargs)
19/12/2016 11:33:22  File "/celery/extractions.py", line 205, in do
19/12/2016 11:33:22    export_schema_to_shapefile_or_mapinfo(year, proj, cities, tmpdir, "MapInfo File", conn, PG_CONNECT_STRING)
19/12/2016 11:33:22  File "/celery/extractions.py", line 107, in export_schema_to_shapefile_or_mapinfo
19/12/2016 11:33:22    run_command(args)
19/12/2016 11:33:22  File "/celery/extractions.py", line 67, in run_command
19/12/2016 11:33:22    raise Exception("Error running %s" % " ".join(args))
19/12/2016 11:33:22Exception: Error running ogr2ogr -where idcom IN ('59001','59002','59003','62893','62894') -a_srs EPSG:4326 -t_srs EPSG:4326 -f MapInfo File /extracts/foncier_2014_mifmid_4326_068b3b1c-b367-48d0-a52c-73281625f498-v_ny9pfj PG:host=database port=5432 user=geoserver dbname=geoserver password=... schemas=foncier_2014 pb0010_local
```

**Comment by fvanderbiest** [comment]
non reproductible
